"""LLM 配置处理：llm.yaml 加载 / flatten / switch provider / env 导出。

迁移自 scripts/init-env.py，保持函数签名与行为不变。
"""
import json
import os
import re
import sys
from pathlib import Path

from lib.config_io import load_env_config_file, save_env_config_file
from lib.logging import (
    COLOR_CYAN, COLOR_GREEN, COLOR_YELLOW, COLOR_RED, COLOR_DARKGRAY, COLOR_RESET,
    info, warn, error, hint,
)

# ============================================================
# 拆分后的配置文件：env.yaml → llm.yaml + mcp.yaml
# ============================================================
LLM_TOP_KEYS = ["llm", "embedding", "tts", "asr", "vision", "misc"]

MARKER_START = "# >>> MCP ENV START (auto-generated by init-env.py) >>>"
MARKER_END = "# <<< MCP ENV END <<<"

PROTOCOL_ENV_MAP = {
    "openai": {
        "base_url": "OPEN_AI_API_BASE_URL",
        "api_key": "OPEN_AI_API_KEY",
        "model": "OPENAI_MODEL",
    },
    "anthropic": {
        "base_url": "ANTHROPIC_BASE_URL",
        "api_key": "ANTHROPIC_AUTH_TOKEN",
        "model": "ANTHROPIC_MODEL",
    },
}

DIRECT_FIELD_KEYS = {"base_url", "api_key", "models"}


def load_split_env_config(project_root: Path, silent: bool = False) -> dict:
    """从 llm.yaml + mcp.yaml 加载并合并配置（向后兼容 env.yaml）。

    优先级：
      1. llm.yaml + mcp.yaml 都存在 → 合并
      2. 只有 llm.yaml → mcp 部分用空 dict
      3. 只有 env.yaml → 直接读 env.yaml（向后兼容）
      4. 都没有 → 报错
    """
    llm_file = project_root / "config" / "llm" / "llm.yaml"
    mcp_file = project_root / "config" / "mcp" / "mcp.yaml"
    env_file = project_root / "env.yaml"

    if llm_file.exists():
        if not silent:
            print(f"{COLOR_GREEN}[READ] {llm_file}{COLOR_RESET}")
        llm_data = load_env_config_file(llm_file) or {}
        mcp_data = {}
        if mcp_file.exists():
            if not silent:
                print(f"{COLOR_GREEN}[READ] {mcp_file}{COLOR_RESET}")
            mcp_data = load_env_config_file(mcp_file) or {}
        merged = {}
        for k in LLM_TOP_KEYS:
            if k in llm_data:
                merged[k] = llm_data[k]
        merged["mcp"] = mcp_data.get("mcp", {})
        # 保留 description
        if "_description" in llm_data:
            merged["_description"] = llm_data["_description"]
        return merged

    if env_file.exists():
        # 向后兼容：直接读 env.yaml
        if not silent:
            print(f"{COLOR_GREEN}[READ] {env_file}{COLOR_RESET}")
        return load_env_config_file(env_file)

    # 都没有
    print(f"{COLOR_RED}[ERROR] Config files not found.{COLOR_RESET}")
    print(f"  Expected: {llm_file} + {mcp_file}")
    print()
    print("Steps:")
    print("  1. Copy template/llm/llm-env-example.yaml to config/llm/llm.yaml")
    print("  2. Copy template/mcp/mcp-env-example.yaml to config/mcp/mcp.yaml")
    print("  3. Fill in real API Keys in config/llm/llm.yaml / config/mcp/mcp.yaml")
    print("  4. Re-run this script")
    sys.exit(1)


def save_split_env_config(project_root: Path, config: dict) -> None:
    """将配置拆分保存回 config/llm/llm.yaml + config/mcp/mcp.yaml。"""
    llm_file = project_root / "config" / "llm" / "llm.yaml"
    mcp_file = project_root / "config" / "mcp" / "mcp.yaml"
    llm_data = {k: v for k, v in (config or {}).items() if k in LLM_TOP_KEYS}
    if "_description" in config:
        llm_data["_description"] = config["_description"]
    mcp_data = {"mcp": (config or {}).get("mcp", {})}
    save_env_config_file(llm_file, llm_data)
    save_env_config_file(mcp_file, mcp_data)


def read_env_config(env_file: Path, silent: bool = False) -> dict:
    """[已弃用] 旧版单文件读取，保留用于向后兼容。"""
    if not env_file.exists():
        print(f"{COLOR_RED}[ERROR] Config file not found: {env_file}{COLOR_RESET}")
        print()
        print("Steps:")
        print("  1. Copy template/llm/llm-env-example.yaml to config/llm/llm.yaml")
        print("  2. Copy template/mcp/mcp-env-example.yaml to config/mcp/mcp.yaml")
        print("  3. Fill in real API Keys in llm.yaml / mcp.yaml")
        print("  4. Re-run this script")
        sys.exit(1)
    if not silent:
        print(f"{COLOR_GREEN}[READ] {env_file}{COLOR_RESET}")
    return load_env_config_file(env_file)


def build_proxy_model_list(env_config: dict) -> str:
    """从 active provider 的 openai 协议收集模型，生成 YAML model_list 条目。"""
    llm = env_config.get("llm", {})
    if not isinstance(llm, dict):
        return "  []"

    active_provider_name = llm.get("_active_provider", "")
    if not active_provider_name or active_provider_name not in llm:
        return "  []"

    provider_value = llm[active_provider_name]
    if not isinstance(provider_value, dict):
        return "  []"

    openai_config = None
    if _is_flat_provider(provider_value):
        openai_config = provider_value
    elif "openai" in provider_value:
        openai_config = provider_value["openai"]

    if not isinstance(openai_config, dict):
        return "  []"

    models = openai_config.get("models", {})
    if not isinstance(models, dict) or not models:
        return "  []"

    provider_base_url = openai_config.get("base_url", "")
    provider_api_key = openai_config.get("api_key", "")

    entries: list[str] = []
    for model_name in models:
        entries.append(
            f"  - model_name: \"{model_name}\"\n"
            f"    litellm_params:\n"
            f"      model: \"{model_name}\"\n"
            f"      custom_llm_provider: openai\n"
            f"      api_base: \"{provider_base_url}\"\n"
            f"      api_key: \"{provider_api_key}\""
        )

    if not entries:
        return "  []"
    return "\n".join(entries)


def _is_flat_provider(provider_value: dict) -> bool:
    return any(k in DIRECT_FIELD_KEYS for k in provider_value)


def flatten_env_config(env_config: dict, active_provider: str, active_protocols: list[str]) -> dict:
    flat = {}
    llm = env_config.get("llm", {})

    if isinstance(llm, dict):
        for provider_name, provider_value in llm.items():
            if provider_name.startswith("_"):
                continue
            if provider_name == "proxy":
                continue
            if not isinstance(provider_value, dict):
                continue
            is_active = provider_name == active_provider

            if _is_flat_provider(provider_value):
                flat_protocol_name = provider_name
                protocols_to_iter = {flat_protocol_name: provider_value}
            else:
                protocols_to_iter = provider_value

            for protocol_name, protocol_value in protocols_to_iter.items():
                if protocol_name.startswith("_"):
                    continue
                if not isinstance(protocol_value, dict):
                    continue
                is_active_protocol = is_active and protocol_name in active_protocols
                if is_active_protocol:
                    tag = f"[ACTIVE] "
                elif is_active:
                    tag = f"[ENABLED] "
                else:
                    tag = f"[        ] "
                print(f"  {COLOR_CYAN}{tag}llm/{provider_name}/{protocol_name}{COLOR_RESET}")

                provider_upper = provider_name.upper().replace("-", "_")
                protocol_upper = protocol_name.upper().replace("-", "_")
                for k, v in protocol_value.items():
                    if k.startswith("_"):
                        continue
                    if k == "models" and isinstance(v, dict):
                        named_key = f"LLM_{provider_upper}_{protocol_upper}_MODELS"
                        flat[named_key] = json.dumps(v, ensure_ascii=False)
                        default_model = next(iter(v.keys()), "")
                        if default_model:
                            default_model_key = f"LLM_{provider_upper}_{protocol_upper}_MODEL"
                            flat[default_model_key] = default_model
                        continue
                    field_upper = k.upper()
                    named_key = f"LLM_{provider_upper}_{protocol_upper}_{field_upper}"
                    flat[named_key] = v

                models_dict = protocol_value.get("models", {})
                default_model = next(iter(models_dict.keys()), "") if isinstance(models_dict, dict) else ""

                if is_active:
                    env_mapping = PROTOCOL_ENV_MAP.get(protocol_name, {})
                    std_model_key = env_mapping.get("model")
                    if std_model_key and default_model:
                        flat[std_model_key] = default_model
                        print(f"    {COLOR_GREEN}models -> {std_model_key} = {default_model}{COLOR_RESET}")
                    for k, v in protocol_value.items():
                        if k.startswith("_") or k == "models":
                            continue
                        std_key = env_mapping.get(k)
                        if std_key:
                            flat[std_key] = v
                            if std_key != k:
                                print(f"    {COLOR_GREEN}{k} -> {std_key}{COLOR_RESET}")
                        else:
                            flat[k] = v

                    if protocol_name == "openai":
                        flat["OPENAI_API_KEY"] = protocol_value.get("api_key", "")

                if is_active_protocol:
                    if default_model:
                        flat[f"LLM_ACTIVE_{protocol_name.upper()}_MODEL"] = default_model
                        flat.setdefault("LLM_ACTIVE_MODEL", default_model)
                    if isinstance(models_dict, dict) and models_dict:
                        flat[f"LLM_ACTIVE_{protocol_name.upper()}_MODELS"] = json.dumps(models_dict, ensure_ascii=False)
                        flat.setdefault("LLM_ACTIVE_MODELS", json.dumps(models_dict, ensure_ascii=False))
                    for k, v in protocol_value.items():
                        if k.startswith("_") or k == "models":
                            continue
                        protocol_active_key = f"LLM_ACTIVE_{protocol_name.upper()}_{k.upper()}"
                        flat[protocol_active_key] = v
                        generic_active_key = f"LLM_ACTIVE_{k.upper()}"
                        if generic_active_key not in flat:
                            flat[generic_active_key] = v
                    flat["LLM_ACTIVE_PROVIDER"] = provider_name
                    flat.setdefault("LLM_ACTIVE_PROTOCOL", protocol_name)

    # --- Codex / Proxy 逻辑 ---
    proxy_config = llm.get("proxy", {}) if isinstance(llm, dict) else {}
    enable_proxy = proxy_config.get("enable", False) if isinstance(proxy_config, dict) else False
    active_provider_name = llm.get("_active_provider", "") if isinstance(llm, dict) else ""

    if enable_proxy:
        flat["LLM_ACTIVE_BASE_URL"] = proxy_config.get("base_url", "http://127.0.0.1:4000/v1")
        flat["LLM_ACTIVE_API_KEY"] = proxy_config.get("api_key", "")
        flat["LLM_CODEX_BASE_URL"] = proxy_config.get("base_url", "http://127.0.0.1:4000/v1")
        flat["LLM_CODEX_API_KEY"] = proxy_config.get("api_key", "")
    elif active_provider_name and active_provider_name in llm:
        active_provider_data = llm[active_provider_name]
        if isinstance(active_provider_data, dict):
            openai_config = None
            if _is_flat_provider(active_provider_data):
                openai_config = active_provider_data
            elif "openai" in active_provider_data:
                openai_config = active_provider_data["openai"]

            if isinstance(openai_config, dict):
                flat["LLM_ACTIVE_BASE_URL"] = openai_config.get("base_url", "")
                flat["LLM_ACTIVE_API_KEY"] = openai_config.get("api_key", "")
            else:
                flat["LLM_ACTIVE_BASE_URL"] = ""
                flat["LLM_ACTIVE_API_KEY"] = ""

            if "codex" in active_provider_data:
                codex_protocol = active_provider_data["codex"]
                if isinstance(codex_protocol, dict):
                    flat["LLM_CODEX_BASE_URL"] = codex_protocol.get("base_url", "http://127.0.0.1:4000/v1")
                    flat["LLM_CODEX_API_KEY"] = codex_protocol.get("api_key", "")
                else:
                    flat["LLM_CODEX_BASE_URL"] = "http://127.0.0.1:4000/v1"
                    flat["LLM_CODEX_API_KEY"] = ""
            else:
                flat["LLM_CODEX_BASE_URL"] = flat.get("LLM_ACTIVE_BASE_URL", "")
                flat["LLM_CODEX_API_KEY"] = flat.get("LLM_ACTIVE_API_KEY", "")
        else:
            flat["LLM_ACTIVE_BASE_URL"] = ""
            flat["LLM_ACTIVE_API_KEY"] = ""
            flat["LLM_CODEX_BASE_URL"] = ""
            flat["LLM_CODEX_API_KEY"] = ""
    else:
        flat["LLM_ACTIVE_BASE_URL"] = ""
        flat["LLM_ACTIVE_API_KEY"] = ""
        flat["LLM_CODEX_BASE_URL"] = ""
        flat["LLM_CODEX_API_KEY"] = ""

    if enable_proxy:
        flat["PROXY_MODEL_LIST"] = build_proxy_model_list(env_config)
    else:
        flat["PROXY_MODEL_LIST"] = "  []"

    for section_key in ("embedding",):
        section_value = env_config.get(section_key, {})
        if not isinstance(section_value, dict):
            continue
        active_section_provider = section_value.get("_active_provider", "")
        for provider_name, provider_value in section_value.items():
            if provider_name.startswith("_"):
                continue
            if not isinstance(provider_value, dict):
                continue
            is_active = provider_name == active_section_provider
            provider_upper = provider_name.upper().replace("-", "_")
            section_upper = section_key.upper()
            for k, v in provider_value.items():
                if k.startswith("_"):
                    continue
                field_upper = k.upper()
                flat[f"{section_upper}_{provider_upper}_{field_upper}"] = v
            if is_active:
                for k, v in provider_value.items():
                    if k.startswith("_"):
                        continue
                    flat[f"{section_upper}_{k.upper()}"] = v

    for section_key in ("tts", "asr", "vision"):
        section_value = env_config.get(section_key, {})
        if not isinstance(section_value, dict):
            continue
        section_upper = section_key.upper()
        for provider_name, provider_value in section_value.items():
            if provider_name.startswith("_") or not isinstance(provider_value, dict):
                continue
            provider_upper = provider_name.upper().replace("-", "_")
            for k, v in provider_value.items():
                if k.startswith("_"):
                    continue
                if k == "models" and isinstance(v, dict):
                    model_keys = list(v.keys())
                    if model_keys:
                        flat.setdefault(f"{section_upper}_{provider_upper}_MODEL", model_keys[0])
                    flat.setdefault(f"{section_upper}_{provider_upper}_MODELS", json.dumps(v, ensure_ascii=False))
                    continue
                if isinstance(v, dict):
                    for sub_k, sub_v in v.items():
                        if sub_k.startswith("_"):
                            continue
                        if sub_k == "models" and isinstance(sub_v, dict):
                            model_keys = list(sub_v.keys())
                            if model_keys:
                                flat.setdefault(f"{section_upper}_{provider_upper}_MODEL", model_keys[0])
                        sub_field_upper = sub_k.upper()
                        flat.setdefault(f"{section_upper}_{provider_upper}_{sub_field_upper}", sub_v)
                else:
                    field_upper = k.upper()
                    flat[f"{section_upper}_{provider_upper}_{field_upper}"] = v

    for section_key in ("mcp", "misc"):
        section_value = env_config.get(section_key, {})
        if not isinstance(section_value, dict):
            continue
        for k, v in section_value.items():
            if k.startswith("_"):
                continue
            flat[k] = v

    return flat


def get_env_entries(flat_config: dict) -> list[tuple[str, str]]:
    entries = []
    for key, value in flat_config.items():
        value_str = str(value).strip() if value is not None else ""
        if not value_str:
            os_value = os.environ.get(key, "").strip()
            if os_value:
                value_str = os_value
                print(
                    f"  {COLOR_DARKGRAY}[FALLBACK] {key} 取自 OS 环境变量{COLOR_RESET}"
                )
        if value_str:
            entries.append((key, value_str))
    return entries


def mask_value(v: str) -> str:
    if len(v) > 20:
        return v[:8] + "..." + v[-8:]
    return v


def get_active_provider(env_config: dict) -> str:
    llm = env_config.get("llm", {})
    if isinstance(llm, dict):
        return llm.get("_active_provider", "")
    return ""


def get_active_protocols(env_config: dict) -> list[str]:
    llm = env_config.get("llm", {})
    if isinstance(llm, dict):
        raw = llm.get("_active_protocol", "openai")
        return [p.strip() for p in str(raw).split("|") if p.strip()]
    return ["openai"]


def list_providers(env_config: dict) -> list[str]:
    llm = env_config.get("llm", {})
    if not isinstance(llm, dict):
        return []
    return [k for k in llm.keys() if not k.startswith("_") and k != "proxy"]


def list_protocols(env_config: dict, provider: str) -> list[str]:
    llm = env_config.get("llm", {})
    provider_cfg = llm.get(provider, {})
    if not isinstance(provider_cfg, dict):
        return []
    return [k for k in provider_cfg.keys() if not k.startswith("_")]


def switch_provider(env_config: dict, provider: str, protocol, env_file: Path) -> dict:
    providers = list_providers(env_config)
    if provider not in providers:
        print(f"{COLOR_RED}[ERROR] Unknown provider: {provider}. Available: {', '.join(providers)}{COLOR_RESET}")
        sys.exit(1)

    available_protocols = list_protocols(env_config, provider)

    if protocol is None:
        current_protocols = get_active_protocols(env_config)
        protocol = "|".join([p for p in current_protocols if p in available_protocols])
        if not protocol:
            protocol = available_protocols[0] if available_protocols else "openai"
    else:
        if protocol not in available_protocols:
            if available_protocols:
                protocol = available_protocols[0]
                print(f"{COLOR_YELLOW}[WARN] Protocol not found for {provider}, using first available: {protocol}{COLOR_RESET}")
            else:
                print(f"{COLOR_RED}[ERROR] No protocols configured for provider: {provider}{COLOR_RESET}")
                sys.exit(1)

    env_config["llm"]["_active_provider"] = provider
    env_config["llm"]["_active_protocol"] = protocol
    # 拆分保存到 llm.yaml + mcp.yaml（向后兼容 env.yaml）
    if env_file.name == "llm.yaml":
        # llm.yaml 在 config/llm/ 下，mcp.yaml 在 config/mcp/ 下
        # save_split_env_config 期望 llm_file 和 mcp_file 在同一目录，
        # 这里直接调用 save_env_config_file 分别保存
        from lib.config_io import save_env_config_file
        mcp_file = env_file.parent.parent / "mcp" / "mcp.yaml"
        llm_config = {"llm": env_config.get("llm", {})}
        mcp_config = {"mcpServers": env_config.get("mcpServers", {})}
        save_env_config_file(env_file, llm_config)
        save_env_config_file(mcp_file, mcp_config)
    else:
        save_env_config_file(env_file, env_config)
    print(f"{COLOR_GREEN}[OK] Active provider switched to: {provider}/{protocol}{COLOR_RESET}")
    return env_config


def invoke_env_step(flat_config: dict, scope: str, force: bool) -> dict:
    scope_labels = {
        "process": "Current session (lost on terminal close)",
        "user": "Current user (persistent, write to shell rc)",
    }

    print(f"{COLOR_CYAN}========================================{COLOR_RESET}")
    print(f"{COLOR_CYAN}  Step: Set Environment Variables{COLOR_RESET}")
    print(f"{COLOR_CYAN}========================================{COLOR_RESET}")
    print()

    if scope not in scope_labels:
        print(f"{COLOR_RED}[ERROR] Unknown scope: {scope}. Use 'process' or 'user'.{COLOR_RESET}")
        sys.exit(1)

    print(f"{COLOR_GREEN}Target scope: {scope} ({scope_labels[scope]}){COLOR_RESET}")

    entries = get_env_entries(flat_config)
    env_map = {k: v for k, v in entries}

    if scope == "user" and not force:
        print()
        print(f"{COLOR_YELLOW}About to write the following env vars to [{scope}]:{COLOR_RESET}")
        for key, value in entries:
            print(f"  {COLOR_YELLOW}{key} = {mask_value(value)}{COLOR_RESET}")
        print()
        confirm = input("Confirm write? (y/n) ").strip().lower()
        if confirm != "y":
            print(f"{COLOR_RED}Cancelled.{COLOR_RESET}")
            sys.exit(0)

    print()
    print(f"{COLOR_GREEN}Setting env vars...{COLOR_RESET}")

    ok = 0
    for key, value in entries:
        os.environ[key] = value
        print(f"  {COLOR_GREEN}[OK]   {key}{COLOR_RESET}")
        ok += 1

    print()
    print(f"  {COLOR_CYAN}Result: {ok} ok, scope=[{scope}]{COLOR_RESET}")

    if scope == "process":
        print(f"  {COLOR_YELLOW}Note: Env vars only valid in current Python process.{COLOR_RESET}")
        print(f"  {COLOR_YELLOW}      For shell persistence, use: --scope user{COLOR_RESET}")
        print(f"  {COLOR_YELLOW}      Or manually: eval $(python3 scripts/init-env.py -a ExportShell){COLOR_RESET}")

    if scope == "user":
        shell_rc = _detect_shell_rc()
        print(f"  {COLOR_GREEN}Writing to shell config: {shell_rc}{COLOR_RESET}")
        _write_shell_rc(shell_rc, env_map, force)

    print()
    return env_map


def _detect_shell_rc() -> Path:
    shell = os.environ.get("SHELL", "")
    if "zsh" in shell:
        return Path.home() / ".zshrc"
    if "bash" in shell:
        bash_profile = Path.home() / ".bash_profile"
        if bash_profile.exists():
            return bash_profile
        return Path.home() / ".bashrc"
    return Path.home() / ".profile"


def _write_shell_rc(shell_rc: Path, env_map: dict, force: bool) -> None:
    content = ""
    if shell_rc.exists():
        content = shell_rc.read_text(encoding="utf-8")

    if MARKER_START in content:
        pattern = re.compile(
            re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END),
            re.DOTALL,
        )
        content = pattern.sub("", content)

    lines = [MARKER_START]
    for key, value in sorted(env_map.items()):
        escaped = value.replace("'", "'\\''")
        lines.append(f"export {key}='{escaped}'")
    lines.append(MARKER_END)

    content = content.rstrip("\n") + "\n\n" + "\n".join(lines) + "\n"

    shell_rc.write_text(content, encoding="utf-8")
    print(f"  {COLOR_GREEN}[OK]   Written to {shell_rc}{COLOR_RESET}")
    print(f"  {COLOR_GREEN}Note: New terminals will auto-load these env vars.{COLOR_RESET}")


def invoke_export_shell(flat_config: dict) -> None:
    entries = get_env_entries(flat_config)
    for key, value in entries:
        escaped = value.replace("'", "'\\''")
        print(f"export {key}='{escaped}'")
